name: A workflow for my Hello World file
on: push
jobs:
  build-job:
    name: supraja workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out code
      run: echo Hello World
     - name: Index.html content
      run: cat index.html
